# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitl < Formula
  desc "AI review of git commits with risk scoring (low|medium|high). BYOK: OpenAI, Ollama, Azure."
  homepage "https://github.com/akomyagin/gitl"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akomyagin/gitl/releases/download/v0.4.3/gitl_0.4.3_darwin_amd64.tar.gz"
      sha256 "19b28d5ccd25bec84c5ee38bbda4113ba2225b7ec472b8c3e9ecf3471abfaccb"

      define_method(:install) do
        bin.install "gitl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akomyagin/gitl/releases/download/v0.4.3/gitl_0.4.3_darwin_arm64.tar.gz"
      sha256 "56d3b04ceb29c255255221f8924caa652e302ee38a0c45236673e7a7322ac16f"

      define_method(:install) do
        bin.install "gitl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akomyagin/gitl/releases/download/v0.4.3/gitl_0.4.3_linux_amd64.tar.gz"
      sha256 "0c02d7c0cfb302f3f8c307c72022d0232d97aa6ff5be650df792672b784da06b"
      define_method(:install) do
        bin.install "gitl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akomyagin/gitl/releases/download/v0.4.3/gitl_0.4.3_linux_arm64.tar.gz"
      sha256 "7e87b6478da13e281b18a02518fb06d0db0cf42ef3e2529285d3220b520d9873"
      define_method(:install) do
        bin.install "gitl"
      end
    end
  end

  test do
    system "#{bin}/gitl", "version"
  end
end
