# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitl < Formula
  desc "AI review of git commits with risk scoring (low|medium|high). BYOK: OpenAI, Ollama, Azure."
  homepage "https://github.com/akomyagin/gitl"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akomyagin/gitl/releases/download/v0.3.1/gitl_0.3.1_darwin_amd64.tar.gz"
      sha256 "5c74a61abdac44f60efafcd3d712312e6f9bb1e9df26cb3dc344f10636e2a407"

      define_method(:install) do
        bin.install "gitl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akomyagin/gitl/releases/download/v0.3.1/gitl_0.3.1_darwin_arm64.tar.gz"
      sha256 "b33973bf31354c1b062c0f3df0ae87e9572a96a1ac55da1cec83cab7a83b8c08"

      define_method(:install) do
        bin.install "gitl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akomyagin/gitl/releases/download/v0.3.1/gitl_0.3.1_linux_amd64.tar.gz"
      sha256 "d1d69b1c6491d4113612a1f00bbd5eaaa8251d724db33fc0578f717623522473"
      define_method(:install) do
        bin.install "gitl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akomyagin/gitl/releases/download/v0.3.1/gitl_0.3.1_linux_arm64.tar.gz"
      sha256 "0bb52b310d4ffbd4dbc4a99b12c51cd5994e0fe12a6a0bdf0648133c8fe37285"
      define_method(:install) do
        bin.install "gitl"
      end
    end
  end

  test do
    system "#{bin}/gitl", "version"
  end
end
